### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by ghost** [CodeNL/MiniTwit#1]
I think this looks cool even though I have no idea how it works. So I wanted to try it out. But there are no linux installation instructions. NOOOOOOOOOOOOOO!!!! :( 
PS: Sorry I haven't been to code club for a while but my parents always seem to plan stuff at the same time as it

**Comment by Gudahtt** [comment]
Hi Jonah! Great point - we should have better install instructions. I'll work on writing those soon.


Basically to install it, you need a version of Python greater than 3.4. Once that is installed, you should be able to use pip (which comes with Python) to install this from the root project directory. You can do that by opening a terminal from the root project directory, then running "`pip install --editable .`".

Once that install has succeeded, you can run it with the command "`FLASK_APP=minitwit flask run`". If you're on Windows, the command would be  "`set FLASK_APP=minitwit`" then the command "`flask run`". It should then run, and be visible on `localhost:5000`.

I'll update the README later to explain this in a bit more detail, and verify that it all works.

**Comment by ghost** [comment]
OK I get it thanks

**Comment by Gudahtt** [comment]
Fixed with PR #2
